name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint (Makefile)
        run: make lint

      - name: Smoke tests
        run: |
          bash scripts/test_local.sh

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run end-to-end (Docker Compose)
        env:
          DB_URL: postgresql+psycopg://app:postgres@postgres:5432/appdb
          REDIS_URL: redis://redis:6379/0
          KAFKA_BOOTSTRAP: kafka:29092
          SCHEMA_REG_URL: http://schema-registry:8081
          OPENSEARCH_URL: http://opensearch:9200
          OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
          ENABLE_KAFKA: 'true'
          TOPIC_PRODUCT_UPDATED: events.catalog.product-updated
          TOPIC_ORDER_CREATED: events.orders.order-created
        run: |
          bash scripts/e2e_local.sh
