name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black==24.4.2 ruff==0.5.5

      - name: Black (check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Smoke tests
        run: |
          bash scripts/test_local.sh

